<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="194" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="194" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
      <class name="coding.Assignment1.IntersectionATest">
        <test-method status="FAIL" signature="combiPosNegz()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="combiPosNegz" duration-ms="35" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[0, 2, 5, -6, 6]] but found [[I@5383967b]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[0, 2, 5, -6, 6]] but found [[I@5383967b]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at coding.Assignment1.IntersectionATest.combiPosNegz(IntersectionATest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- combiPosNegz -->
        <test-method status="PASS" signature="empty()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="empty" duration-ms="2" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- empty -->
        <test-method status="PASS" signature="negative()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="negative" duration-ms="3" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negative -->
        <test-method status="PASS" signature="nullArr()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="nullArr" duration-ms="2" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nullArr -->
        <test-method status="PASS" signature="positive()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="positive" duration-ms="5" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positive -->
        <test-method status="FAIL" signature="zerko()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="zerko" duration-ms="8" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[0]] but found [[I@527740a2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[0]] but found [[I@527740a2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at coding.Assignment1.IntersectionATest.zerko(IntersectionATest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- zerko -->
        <test-method status="FAIL" signature="zero()[pri:0, instance:coding.Assignment1.IntersectionATest@5f375618]" name="zero" duration-ms="2" started-at="2019-06-29T00:02:06Z" finished-at="2019-06-29T00:02:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[0]] but found [[I@370736d9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[0]] but found [[I@370736d9]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at coding.Assignment1.IntersectionATest.zero(IntersectionATest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- zero -->
      </class> <!-- coding.Assignment1.IntersectionATest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
